// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSqSa2E4WsXKpADiIijeUIJaT53XSFtNg',
    appId: '1:326230137775:web:56743ba31aec3c63c9ad5a',
    messagingSenderId: '326230137775',
    projectId: 'baithigiuaki-fd860',
    authDomain: 'baithigiuaki-fd860.firebaseapp.com',
    storageBucket: 'baithigiuaki-fd860.appspot.com',
    measurementId: 'G-RPEDV563GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBow2TeIwS8nxQyJOqLDiKHGjaRa9hGdqc',
    appId: '1:326230137775:android:6411c0b44812d3dcc9ad5a',
    messagingSenderId: '326230137775',
    projectId: 'baithigiuaki-fd860',
    storageBucket: 'baithigiuaki-fd860.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4xoue2H0IKY2bNA-8y1sgqtQ3URtav_s',
    appId: '1:326230137775:ios:e0b0fb3f4f1b22afc9ad5a',
    messagingSenderId: '326230137775',
    projectId: 'baithigiuaki-fd860',
    storageBucket: 'baithigiuaki-fd860.appspot.com',
    iosBundleId: 'com.example.baithigiuaki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4xoue2H0IKY2bNA-8y1sgqtQ3URtav_s',
    appId: '1:326230137775:ios:e0b0fb3f4f1b22afc9ad5a',
    messagingSenderId: '326230137775',
    projectId: 'baithigiuaki-fd860',
    storageBucket: 'baithigiuaki-fd860.appspot.com',
    iosBundleId: 'com.example.baithigiuaki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSqSa2E4WsXKpADiIijeUIJaT53XSFtNg',
    appId: '1:326230137775:web:3c419e94e35a9542c9ad5a',
    messagingSenderId: '326230137775',
    projectId: 'baithigiuaki-fd860',
    authDomain: 'baithigiuaki-fd860.firebaseapp.com',
    storageBucket: 'baithigiuaki-fd860.appspot.com',
    measurementId: 'G-1X7BJT2EQP',
  );
}
